project:
  type: book
  output-dir: docs

toc: true
number-sections: true
top-level-division: part
toc-depth: 3
number-depth: 4
bibliography: book.bib
csl: C:/Users/Xinli/Documents/ims.csl

crossref:
  labels: arabic        # (default is arabic)
  subref-labels: roman i # (default is alpha a)

execute:
  freeze: auto

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

jupyter: base23

format:
  html:
    theme: 
      - cosmo
    code-block-bg: true
    # code-block-border-left: true #"#31BAE9"
    code-line-numbers: true
    highlight-style: atom-one

book:
  title: "Python/R for Data Science"
  subtitle: "Lecture notes for Spring 2023 at Arkansas Tech University"
  author: "Weijia Jia & Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd
    - part: "Part I: Python"
      chapters: 
        - contents/1/01-.qmd
        - contents/2/02-.qmd
        - contents/3/03-.qmd
        - contents/4/04-.qmd
        - contents/5/05-.qmd
        - contents/6/06-.qmd
    - part: "Part II: R"
      chapters:
        - contents/7/07-.qmd
        - contents/8/08-.qmd
    - contents/references.qmd
  appendices:
    - contents/app/setup.qmd
    - contents/app/path.qmd
    - contents/app/virtenv.qmd
    - contents/app/concepts.qmd
    - contents/app/r.qmd
  sidebar:
    style: floating
    pinned: true
    align: center
    border: true
    search: true
    collapse-level: 1
  navbar:
    subtitle: "Spring 2023"
  page-navigation: true


    



